In [1]:
import pandas as pd

In [2]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annotations',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'from_dummies',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [3]:
df = pd.read_csv('retail supermarkets.csv' , index_col=0)
df

FileNotFoundError: [Errno 2] No such file or directory: 'retail supermarkets.csv'

In [ ]:
df.shape

In [ ]:
df.shape[0]

In [ ]:
df.shape[1]

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.head()

In [ ]:
df.head(1)

In [ ]:
df.tail()

In [ ]:
df.tail(15)

**loc (Label-based indexing)** 
Syntax: `df.loc[row_label, column_label]`

In [ ]:

df.head()

In [ ]:
df.loc[2]

In [16]:

df.loc[2,'Postal Code']

90036

In [17]:
df

,Tracking_NO,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,5,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9990,9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9991,9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9992,9993,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9993,9994,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

In [60]:
df1.loc[1,'Sales']

261.96

In [50]:
df1 = pd.read_csv('retail supermarket.csv',index_col=0)
df1

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Tracking_NO,,,,,,,,,,,,,
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9990,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,25.2480,3,0.20,4.1028
9991,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,91.9600,2,0.00,15.6332
9992,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,258.5760,2,0.20,19.3932
9993,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,29.6000,4,0.00,13.3200
9994,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,243.1600,2,0.00,72.9480

**iloc (Integer-based indexing)** `Syntax: df.iloc[row_index, column_index]`

In [38]:
df.iloc[2]

Tracking_NO                   3
Ship Mode          Second Class
Segment               Corporate
Country           United States
City                Los Angeles
State                California
Postal Code               90036
Region                     West
Category        Office Supplies
Sub-Category             Labels
Sales                     14.62
Quantity                      2
Discount                    0.0
Profit                   6.8714
Name: 2, dtype: object

In [86]:
df.iloc[0,12]

41.9136

In [96]:
df.loc[:10]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Tracking_NO,,,,,,,,,,,,,
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [84]:
df.loc[1:10]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Tracking_NO,,,,,,,,,,,,,
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [72]:
df.iloc[1:10]

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
Tracking_NO,,,,,,,,,,,,,
2,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
3,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
5,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164
6,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,48.8600,7,0.00,14.1694
7,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,7.2800,4,0.00,1.9656
8,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,907.1520,6,0.20,90.7152
9,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,18.5040,3,0.20,5.7825
10,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,114.9000,5,0.00,34.4700

In [ ]:
df.iloc[0:10,:7]

In [64]:
df.loc[0:10,'Segment']

0      Consumer
1      Consumer
2     Corporate
3      Consumer
4      Consumer
5      Consumer
6      Consumer
7      Consumer
8      Consumer
9      Consumer
10     Consumer
Name: Segment, dtype: object

In [ ]:
df.loc[2:10,:'Country']

In [ ]:
df1 = pd.read_csv('retail supermarket.csv',index_col=1)
df1

In [ ]:
df1.loc['Consumer']

In [ ]:
df1.loc['Consumer','Ship Mode':]

In [ ]:
df.loc[2:10,['Segment','Category','Ship Mode']]

In [ ]:
df.loc[[2,10],['Segment','Category']]

In [ ]:
df.loc[[2,10],['Profit','Discount']]

In [ ]:
df.iloc[[2,10]]

In [ ]:
df.iloc[[2,10],[1,7]]

In [ ]:
df['City']

In [ ]:
# pd.options.display.max_rows = None

In [ ]:
df['City']

In [ ]:
df[['Country','Postal Code','Category']]

In [ ]:
df[['Country','Postal Code','Category']].head()

In [ ]:
df.head(1)

In [ ]:
df.drop('Postal Code')

In [ ]:
df.head(1)

In [ ]:
df.drop('Postal Code',axis = 1,inplace = True)

In [ ]:
df.head(1)

In [ ]:
df

In [ ]:
df.drop(9993,inplace = True)

In [ ]:
df

In [ ]:
df.drop(9990,inplace = True)

In [ ]:
df

In [ ]:
df2 = pd.read_csv('retail supermarket.csv',header=None)
df2

In [ ]:
df3 = pd.read_csv('retail supermarket.csv',header=1)
df3

# Logical Operators in Pandas:
    * & (and)
    * | (or)
    * ~ (not)

In [ ]:
df['State'] == 'Florida'

In [ ]:
df[df['State'] == 'Florida']

In [ ]:
df['Category'].unique()

In [ ]:
df[df['Category'] == 'Technology']

In [ ]:
df[(df['State'] == 'Florida') & (df['Category'] == 'Technology')]

In [ ]:
df[(df['State'] == 'Florida') | (df['State'] == 'California')]

In [ ]:
(df['State'] == 'Florida') ~(df['Category'] == 'Technology')

In [ ]:
(df['State'] == 'Florida') & ~(df['Category'] == 'Technology')

In [ ]:
df[(df['State'] == 'Florida') & ~(df['Category'] == 'Technology')]

In [ ]:
df[(df['State'] == 'Florida') | ~(df['Category'] == 'Technology')]